export const profile = {
  name: 'Arfey Moreno Jazzua',
  title: 'Full Stack Developer',
  subtitle: 'Membangun pengalaman digital yang bermakna',
  bio: 'Saya mengembangkan solusi elegan di persimpangan desain dan engineering, menciptakan aplikasi yang indah dan performan.',
  email: 'morenoreno166@gmail.com',
  location: 'Jakarta, Indonesia',
}

export const disciplines = [
  {
    id: 1,
    title: 'Pengembangan Frontend',
    description: 'Menciptakan antarmuka pengguna yang indah dan responsif dengan React dan Next.js',
    icon: '💎',
  },
  {
    id: 2,
    title: 'Pengembangan Backend',
    description: 'Membangun API dan layanan yang scalable dengan Node.js dan TypeScript',
    icon: '⚙️',
  },
  {
    id: 3,
    title: 'Desain UI/UX',
    description: 'Merancang antarmuka intuitif dengan fokus pada pengalaman pengguna',
    icon: '🎨',
  },
  {
    id: 4,
    title: 'Desain Database',
    description: 'Merancang database yang efisien dengan PostgreSQL dan MongoDB',
    icon: '🗄️',
  },
  {
    id: 5,
    title: 'DevOps & Deployment',
    description: 'Mengotomatisasi deployment dan infrastruktur dengan alat modern',
    icon: '🚀',
  },
]

export const projects = [
  {
    id: 1,
    title: 'MiJurnal - Platform Jurnal Siswa',
    description: 'Platform jurnal digital komprehensif untuk siswa melacak aktivitas pembelajaran, mengelola tugas, dan menjaga jadwal belajar yang konsisten.',
    fullDescription: {
      definition: 'MiJurnal adalah platform jurnal digital yang berpusat pada siswa dirancang untuk membantu siswa mendokumentasikan perjalanan pendidikan, melacak kemajuan, dan mempertahankan akuntabilitas dalam proses pembelajaran mereka.',
      purpose: 'Untuk menyediakan platform terpusat di mana siswa dapat: mencatat aktivitas pembelajaran harian, memantau kemajuan tugas, menetapkan dan melacak tujuan belajar, mengelola jadwal, dan merefleksikan pertumbuhan akademik mereka seiring waktu.',
      implementation: {
        features: [
          'Antarmuka logging aktivitas harian dan journaling',
          'Pelacakan tugas dan penugasan dengan manajemen tenggat waktu',
          'Dasbor analitik kemajuan dan wawasan pembelajaran',
          'Organisasi jadwal dan timetable',
          'Organisasi berbasis kategori dan tag',
          'Fungsionalitas pencarian dan filter',
          'Kemampuan ekspor data dan pelaporan',
        ],
        technical: 'Dibangun dengan React.js untuk frontend responsif dengan UI/UX intuitif, dan backend Laravel menyediakan API RESTful yang robust dengan manajemen database, autentikasi, dan validasi data.',
      },
    },
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-5ZVP1Uj8lofmaNTvFlmVUEEHzikQEO.png',
    tags: ['React.js', 'Laravel', 'MySQL', 'RESTful API', 'Responsive Design'],
    link: '#',
    category: 'web',
  },
  {
    id: 2,
    title: 'Manajemen Magang - Sistem Manajemen Magang',
    description: 'Sistem manajemen magang terintegrasi yang memungkinkan perusahaan menyederhanakan seluruh siklus hidup program magang dari pendaftaran hingga evaluasi.',
    fullDescription: {
      definition: 'Manajemen Magang adalah platform manajemen magang tingkat enterprise yang menyediakan otomasi workflow lengkap untuk institusi pendidikan dan perusahaan yang mengelola program magang.',
      purpose: 'Untuk memfasilitasi manajemen program magang yang efisien dengan: menyederhanakan pendaftaran dan penempatan siswa, mengotomatisasi penugasan mentor, melacak kemajuan magang, mengelola evaluasi, dan menyediakan pelaporan dan analitik komprehensif.',
      implementation: {
        features: [
          'Portal registrasi dan aplikasi siswa',
          'Manajemen perusahaan dan posisi',
          'Pencocokan mentor dan magang otomatis',
          'Pelacakan kemajuan dan manajemen milestone',
          'Form evaluasi dan penilaian digital',
          'Notifikasi real-time dan komunikasi',
          'Dasbor analitik dan pelaporan komprehensif',
          'Manajemen dokumen dan generasi sertifikat',
          'Metrik kinerja dan wawasan',
        ],
        technical: 'Frontend dibangun dengan React.js memberikan UI modern dan responsif untuk siswa dan administrator. Backend didukung oleh Laravel menyediakan autentikasi aman, logika bisnis, endpoint API, dan manajemen database dengan kontrol akses berbasis peran.',
      },
    },
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-wg5QjvD7YNwKieR8iCmuV1q3qa6bU1.png',
    tags: ['React.js', 'Laravel', 'MySQL', 'Authentication', 'Dashboard'],
    link: '#',
    category: 'web',
  },
  {
    id: 3,
    title: 'Perpustakaan - Sistem Manajemen Perpustakaan',
    description: 'Sistem informasi perpustakaan komprehensif untuk mengelola buku, siswa, kelas, peminjaman, pengembalian, dan perhitungan denda keterlambatan.',
    fullDescription: {
      definition: 'Perpustakaan adalah sistem manajemen perpustakaan full-stack yang dirancang untuk memusatkan dan mengotomatisasi semua operasi perpustakaan untuk sekolah dan institusi, menangani inventaris buku, data siswa, transaksi peminjaman, dan manajemen pengembalian.',
      purpose: 'Untuk menyederhanakan operasi perpustakaan dengan: menyediakan manajemen katalog buku digital, mengotomatisasi proses peminjaman dan pengembalian, menghitung denda keterlambatan secara otomatis, mengelola akun perpustakaan siswa, dan mempertahankan riwayat transaksi lengkap.',
      implementation: {
        features: [
          'Operasi CRUD untuk buku, siswa, kelas, dan transaksi',
          'Peminjaman buku multi-item dengan pelacakan detail',
          'Pemrosesan pengembalian otomatis dan perhitungan denda keterlambatan',
          'Autentikasi dan otorisasi pengguna berbasis JWT',
          'Unggah dan penyimpanan gambar sampul buku',
          'Riwayat transaksi lengkap dan pelaporan',
          'Dasbor admin untuk manajemen sistem',
          'Hubungan database untuk integritas data perpustakaan',
          'Fungsionalitas pencarian dan filter untuk akses cepat',
        ],
        technical: 'Backend dibangun dengan Laravel 10 dan PHP 8.1 menggunakan Eloquent ORM untuk operasi database dan autentikasi JWT. Frontend dikembangkan dengan Next.js menyediakan antarmuka pengguna yang responsif dan intuitif. Database MySQL menyimpan semua data perpustakaan dengan struktur relasional yang tepat. PHPUnit digunakan untuk pengujian API.',
      },
    },
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-bIWLhwepBqRZtDTnv49qeuKqhUnBk4.png',
    tags: ['Next.js', 'Laravel 10', 'MySQL', 'JWT', 'PHP 8.1', 'Eloquent ORM'],
    link: '#',
    category: 'web',
  },
  {
    id: 4,
    title: 'KINETIC - Marketplace Sneaker Online',
    description: 'Platform e-commerce full-stack premium yang khusus dalam sneaker terautentikasi dengan autentikasi JWT, unggah bukti pembayaran, dan workflow persetujuan admin.',
    fullDescription: {
      definition: 'KINETIC adalah platform e-commerce modern yang didedikasikan untuk sneaker premium terautentikasi, menampilkan pengalaman berbelanja end-to-end lengkap dengan pemrosesan pembayaran aman dan manajemen transaksi admin.',
      purpose: 'Untuk menciptakan marketplace sneaker premium yang dikurasi yang: memberikan pelanggan dengan pilihan produk terautentikasi dan filter pencarian detail, mengelola keranjang belanja dan checkout aman, menangani unggah bukti pembayaran digital, memungkinkan persetujuan transaksi admin, dan mempertahankan riwayat pesanan komprehensif.',
      implementation: {
        features: [
          'Autentikasi pengguna dengan token JWT untuk akses API aman',
          'Katalog produk dengan informasi detail dan filtering',
          'Pencarian produk canggih dengan filter kategori dan harga',
          'Manajemen keranjang belanja dengan kontrol jumlah',
          'Proses checkout dengan unggah bukti pembayaran',
          'Dasbor admin untuk workflow persetujuan transaksi',
          'Riwayat pesanan dan pelacakan untuk pengguna',
          'Kontrol akses berbasis peran (peran Admin & Customer)',
          'Desain responsif untuk perangkat desktop dan mobile',
          'Update ketersediaan produk real-time',
        ],
        technical: 'Frontend dikembangkan dengan Next.js untuk performa optimal dan SEO. Backend diimplementasikan dengan Laravel 10 sebagai REST API yang scalable menyediakan autentikasi JWT, manajemen produk, penanganan pembayaran, dan pemrosesan pesanan. Middleware berbasis peran memastikan kontrol akses aman antara operasi pelanggan dan admin.',
      },
    },
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-04-06%20221638-YWf9lBt5j7fzzCctIHAGLxfzAfjRCp.png',
    tags: ['Next.js', 'Laravel 10', 'MySQL', 'JWT Auth', 'REST API', 'E-Commerce'],
    link: '#',
    category: 'web',
  },
  {
    id: 5,
    title: 'KINETIC - Sistem Desain UI/UX',
    description: 'Sistem desain UI/UX komprehensif untuk marketplace sneaker KINETIC termasuk login, homepage, pencarian produk, dan antarmuka profil pengguna.',
    fullDescription: {
      definition: 'Sistem Desain UI/UX KINETIC adalah kerangka desain lengkap yang mendefinisikan standar visual, pola interaksi, dan panduan pengalaman pengguna untuk platform e-commerce sneaker premium.',
      purpose: 'Untuk membangun bahasa desain dan pengalaman pengguna yang konsisten di semua layar aplikasi dengan: membuat pola komponen yang dapat digunakan kembali, mendefinisikan standar interaksi, memastikan hierarki visual dan konsistensi merek, dan mengoptimalkan alur pengguna untuk pengalaman berbelanja yang mulus.',
      implementation: {
        features: [
          'Antarmuka Login & Registrasi dengan validasi form',
          'Homepage dengan bagian hero, produk unggulan, dan item trending',
          'Antarmuka pencarian dan filtering produk canggih',
          'Halaman detail produk dengan galeri gambar dan ulasan',
          'Desain alur keranjang belanja dan checkout',
          'Halaman profil pengguna dan riwayat pesanan',
          'Dasbor admin untuk manajemen transaksi',
          'Pola desain responsif untuk semua ukuran layar',
          'Variasi tema gelap dan terang',
          'Komponen interaktif dan status hover',
        ],
        technical: 'Dirancang menggunakan alat desain UI standar industri dengan wireframe komprehensif dan mockup fidelitas tinggi. Mencakup layout desktop dan responsif, spesifikasi komponen detail, definisi palet warna, panduan tipografi, dan pola interaksi untuk implementasi yang mulus ke frontend React/Next.js.',
      },
    },
    image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Screenshot%202026-04-06%20112746-uf6qqD69dp1TsxetELi3jhHpknR1P4.png',
    tags: ['UI Design', 'UX Design', 'Figma', 'Design System', 'Responsive Design', 'Prototyping'],
    link: '#',
    category: 'design',
  },

]

export const experience = [
  {
    id: 1,
    role: 'Pengembangan Web Full Stack',
    company: 'Sekolah Pemrograman (2023 - 2026)',
    period: '2023 - 2026',
    description: 'Pelatihan intensif dalam pengembangan web full-stack mencakup teknologi frontend dan backend dengan pengalaman proyek hands-on.',
    achievements: [
      'Menguasai framework Laravel untuk pengembangan API backend',
      'Mengembangkan multiple projects menggunakan Next.js dan React',
      'Mahir dalam desain dan optimasi database MySQL dan PostgreSQL',
      'Membangun 5+ aplikasi full-stack dengan integrasi frontend-backend lengkap',
      'Mengimplementasikan sistem autentikasi dan RESTful APIs',
      'Mempelajari best practices industri untuk clean code dan arsitektur scalable',
    ],
  },
  {
    id: 2,
    role: 'Pengembangan Frontend',
    company: 'Kurikulum Sekolah',
    period: '2023 - 2024',
    description: 'Pelatihan khusus dalam teknologi frontend modern dan desain web responsif.',
    achievements: [
      'Kemampuan advanced dalam React dan Next.js 13+ dengan App Router',
      'Menguasai TypeScript untuk pengembangan type-safe',
      'Expert dalam TailwindCSS untuk desain UI modern',
      'Membuat aplikasi web yang responsif dan accessible',
    ],
  },
  {
    id: 3,
    role: 'Manajemen Backend & Database',
    company: 'Kurikulum Sekolah',
    period: '2024 - 2026',
    description: 'Pelatihan mendalam dalam pengembangan backend dan sistem manajemen database.',
    achievements: [
      'Pengembangan Laravel dan PHP tingkat expert',
      'Mahir dalam Node.js dan Express untuk pengembangan API',
      'Kemampuan SQL advanced dengan MySQL dan PostgreSQL',
      'Desain database, optimasi, dan implementasi keamanan',
      'Pola desain RESTful dan API',
    ],
  },
]

export const skills = {
  frontend: ['React', 'Next.js', 'TypeScript', 'TailwindCSS', 'Vue.js'],
  backend: ['Laravel', 'Node.js', 'Express', 'NestJS', 'REST APIs'],
  database: ['MySQL', 'PostgreSQL', 'MongoDB', 'Eloquent ORM'],
  tools: ['Git', 'Docker', 'AWS', 'GitHub Actions', 'Vercel', 'Linux'],
  design: ['Figma', 'Desain UI/UX', 'Design Systems', 'Desain Responsif', 'Aksesibilitas'],
}

export const certificates = [
  {
    id: 1,
    title: 'Memulai Pemrograman Dengan Java',
    issuer: 'Dicoding',
    date: '06 Agustus 2025',
    validUntil: '06 Agustus 2028',
    certificateNo: 'GRX5JKN5KX0M',
    description: 'Sertifikat untuk menyelesaikan kursus Java Programming dasar dengan standar industri. Mencakup Java Dasar, Control Flow, Collection Type, Object-Oriented Programming (OOP), Common Class, Exception Handling, Input Output, Date Time, dan Studi Kasus praktis dengan total 15 jam pembelajaran.',
    link: 'https://dicoding.com/certificates/GRX5JKN5KX0M',
    image: '/certificates/java-certificate.jpg',
  },
  {
    id: 2,
    title: 'Memulai Pemrograman Dengan C',
    issuer: 'Dicoding',
    date: '08 April 2026',
    validUntil: '08 April 2029',
    certificateNo: '07Z670L9JPQR',
    description: 'Sertifikat untuk menyelesaikan kursus Pemrograman C dasar dengan standar industri. Mencakup Pengenalan C, Variabel, Tipe Data, Konstanta, Operasi Dasar, Instruksi Kondisional, Instruksi Pengulangan, Array, Fungsi dan Prosedur dengan total 15 jam pembelajaran.',
    link: 'https://dicoding.com/certificates/07Z670L9JPQR',
    image: '/certificates/c-certificate.jpg',
  },
  {
    id: 3,
    title: 'Belajar Prinsip Pemrograman SOLID',
    issuer: 'Dicoding',
    date: '08 April 2026',
    validUntil: '08 April 2029',
    certificateNo: 'GRX5WOGRKZ0M',
    description: 'Sertifikat untuk menyelesaikan kursus Prinsip Pemrograman SOLID dengan standar industri. Mencakup Object-Oriented Programming (OOP), Relasi pada OOP, Software Design Principle, dan kelima prinsip SOLID (Single Responsibility, Open Closed, Liskov Substitution, Interface Segregation, Dependency Inversion) dengan total 15 jam pembelajaran.',
    link: 'https://dicoding.com/certificates/GRX5WOGRKZ0M',
    image: '/certificates/solid-certificate.jpg',
  },
  {
    id: 4,
    title: 'HTML Essentials',
    issuer: 'Cisco Networking Academy',
    date: '08 April 2026',
    certificateNo: 'd840870b-fe35-425b-8f81-40e2d6eb3bca',
    description: 'Sertifikat dari Cisco Networking Academy untuk menyelesaikan kursus HTML Essentials. Pembelajaran mengenai dasar-dasar HTML dan pemahaman struktur halaman web modern dengan standar industri profesional.',
    link: '#',
    image: '/certificates/html-certificate.jpg',
  },
  {
    id: 5,
    title: 'Backend Development',
    issuer: 'MindLuster',
    date: '09 April 2026',
    certificateNo: 'c744ae4f',
    description: 'Sertifikat dari MindLuster untuk menyelesaikan kursus Backend Development. Pembelajaran mendalam tentang pengembangan backend, arsitektur aplikasi server-side, REST APIs, database design, dan best practices backend development dengan standar industri profesional.',
    link: '#',
    image: '/certificates/backend-certificate.jpg',
  },
  {
    id: 6,
    title: 'Disable JavaScript using Developer Tools',
    issuer: 'MindLuster',
    date: '08 April 2026',
    certificateNo: '2d0f7df7',
    description: 'Sertifikat dari MindLuster untuk menyelesaikan kursus tentang cara disable JavaScript menggunakan browser developer tools. Pembelajaran mendalam tentang debugging, browser DevTools, browser features, dan web development tools profesional.',
    link: '#',
    image: '/certificates/javascript-certificate.jpg',
  },
]

export const socialLinks = [
  {
    name: 'GitHub',
    url: 'https://github.com',
    icon: 'GitHub',
  },
  {
    name: 'LinkedIn',
    url: 'https://linkedin.com',
    icon: 'Linkedin',
  },
  {
    name: 'Twitter',
    url: 'https://twitter.com',
    icon: 'Twitter',
  },
  {
    name: 'Email',
    url: 'mailto:arfey@example.com',
    icon: 'Mail',
  },
]
